
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
version="0.0.5"
name="taskcli"

[project.scripts]
taskcli = "taskcli.main:main"
tt = "taskcli.main:main"