# Taskfile
version: 3



tasks:
  default: task --list
  init-venv:
    desc: Initialize virtual environment
    cmds:
      - python3.11 -m venv venv
      - source venv/bin/activate && pip install --upgrade setuptools wheel build twine
      - source venv/bin/activate && pip install -r requirements.txt

  pre-commit:
    desc: Run pre-commit
    aliases:
      - pc
    cmds:
      - task: all-examples
      - task: black
      - task: test

  black:
    desc: Run black
    cmds:
      - black src/taskcli/*.py test/*.py examples/*.py

  build:
    desc: build package
    cmds:
      - source venv/bin/activate && python -m build

  test:
    desc: Run tests
    aliases: [t]
    cmds:
      - source venv/bin/activate && python -m unittest discover -s examples -p "*_test.py"

  all-examples:
    desc: Run all examples
    aliases: [ae]
    cmds:
      - ./examples/example1.py
      - ./examples/example1.py hello-world -h
      - ./examples/example1.py hello-world -hh
      - ./examples/example1.py hello-world -n 5 -m "Hello!"
      - ./examples/example1.py hello-world -n 1


  upload-prod:
    desc: Upload to PyPI
    cmds:
      - source venv/bin/activate && python -m twine upload dist/taskcli-*

  upload-test:
    desc: Upload to Test PyPI
    cmds:
      - source venv/bin/activate && python -m twine upload --repository testpypi dist/taskcli-*