# Taskfile
version: 3

tasks:
  default: task --list
  init-venv:
    desc: Initialize virtual environment
    cmds:
      - python3.11 -m venv venv
      - source venv/bin/activate && pip install --upgrade setuptools wheel build twine
      - source venv/bin/activate && pip install -r requirements.txt

  pre-commit:
    desc: Run pre-commit
    aliases:
      - pc
    cmds:
      - black src/taskcli/*.py test/*.py
      - task: test

  build:
    desc: build package
    cmds:
      - source venv/bin/activate && python -m build

  test:
    desc: Run tests
    aliases: [t]
    cmds:
      - source venv/bin/activate && python -m unittest discover


  upload-prod:
    desc: Upload to PyPI
    cmds:
      - source venv/bin/activate && python -m twine upload dist/taskcli-*

  upload-test:
    desc: Upload to Test PyPI
    cmds:
      - source venv/bin/activate && python -m twine upload --repository testpypi dist/taskcli-*