# Taskfile
version: 3

tasks:

  default: task --list
  init-venv:
    aliases: [iv]
    desc: Initialize virtual environment
    status:
      - test -d venv
    cmds:
      - test -d venv && rm -rf venv || true
      - python3 -m venv venv
      - source venv/bin/activate && pip install -e .
      - source venv/bin/activate && pip install -r requirements.txt

  init-venv-build:
    aliases: [ivb]
    desc: Initialize build virtual environment
    env:
      VENV: source venv-build/bin/activate &&
    status:
      - test -d venv-build
    cmds:
      - test -d venv-build && rm -rf venv-build || true
      - python3 -m venv venv-build
      - source venv-build/bin/activate && python3 -m venv venv-build
      - source venv-build/bin/activate && pip install --upgrade setuptools wheel build twine
      - source venv-build/bin/activate && source venv/bin/activate && pip install -r requirements.txt

  pre-commit:
    desc: Run pre-commit
    aliases:
      - pc
    cmds:
      - task: all-examples
      - task: black
      - task: test

  black:
    desc: Run black
    cmds:
      - . venv/bin/activate && black src/taskcli/*.py tests/*.py examples/*.py --line-length 120

  build:
    desc: build package
    cmds:
      - test -d dist && rm -rf dist || true
      - . venv-build/bin/activate && python -m build

  test:
    desc: Run tests
    aliases: [t]
    cmds:
      - task: black
      - . venv/bin/activate && python -m unittest discover -s tests -p "*_test.py" {{.CLI_ARGS}} -v
      - . venv/bin/activate && python -m unittest discover -s examples -p "*_test.py" {{.CLI_ARGS}} -v
      - . venv/bin/activate && examples/defaulttask.py | grep "Hello"
      - . venv/bin/activate && examples/example1.py -a 1 -b 2
      - . venv/bin/activate && examples/example1.py -h


  all-examples:
    desc: Run all examples
    aliases: [ae]
    cmds:
      - . venv/bin/activate && ./examples/example1.py
      - . venv/bin/activate && ./examples/example1.py hello-world -h
      - . venv/bin/activate && ./examples/example1.py hello-world -hh
      - . venv/bin/activate && ./examples/example1.py hello-world -n 5 -m "Hello!"
      - . venv/bin/activate && ./examples/example1.py hello-world -n 1


  upload-prod:
    desc: Upload to PyPI
    cmds:
      - . venv-build/bin/activate && python -m twine upload dist/taskcli-*

  upload-test:
    desc: Upload to Test PyPI
    cmds:
      - . venv-build/bin/activate && python -m twine upload --repository testpypi dist/taskcli-*