#!/usr/bin/env python

from taskcli import task, cli


@task()
def hello_world(num: int, message="Hello, World!"):
    """This task prints "Hello, World!" message -n/--num times.
    num: number of times to print the message.
         The short version of this flag, -n, is autogenerated
         from the first letter of the parameter name.
         The 'num' parameter does not have a default value in this example,
         it is therefore required on the CLi.

    message: the message to print.
        It has a default: 'Hello, World!', it is therefor optional
        Can also be set with -m (first letter of the parameter name).

    """
    for x in range(num):
        print(message)


@task()
def My_task(foobar):
    """This task does nothing."""
    pass


# to run the example:
#   pip install taskcli
#   ./examples/example1.py hello_world -n 3

if __name__ == "__main__":
    cli()

